 name: unidata-workshop
 channels:
   - https://conda.anaconda.org/conda-forge
 dependencies:
   - python=3
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - networkx
   - netcdf4
   - owslib
   - metpy
   - pint<0.7
   - siphon
   - xarray
   - anaconda-client

