 name: unidata-workshop
 channels:
   - conda-forge
 dependencies:
   - python=3
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - netcdf4
   - owslib
   - metpy
   - pint
   - shapely
   - siphon
   - xarray
   - pip
   - ffmpeg
   - pytest
   - mplcursors
