 name: unidata-workshop
 channels:
   - https://conda.binstar.org/conda-forge
   - https://conda.binstar.org/scitools
 dependencies:
   - python=3
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - networkx
   - netcdf4
   - owslib
   - metpy
   - siphon
   - xarray
   - anaconda-client
   # Until 4.2.2 comes out
   - jupyter_client!=4.2.1

